"""create biodatas table

Revision ID: 023fd7085719
Revises: 22f795629a59
Create Date: 2026-07-22 23:01:36.369879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023fd7085719'
down_revision: Union[str, Sequence[str], None] = '22f795629a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biodatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.String(length=30), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('religion', sa.String(length=50), nullable=False),
    sa.Column('caste', sa.String(length=100), nullable=False),
    sa.Column('height', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('father_name', sa.String(length=100), nullable=False),
    sa.Column('mother_name', sa.String(length=100), nullable=False),
    sa.Column('siblings', sa.String(length=100), nullable=False),
    sa.Column('family_type', sa.String(length=50), nullable=False),
    sa.Column('highest_qualification', sa.String(length=100), nullable=False),
    sa.Column('college', sa.String(length=150), nullable=False),
    sa.Column('university', sa.String(length=150), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('annual_income', sa.String(length=100), nullable=False),
    sa.Column('preferred_age', sa.String(length=50), nullable=False),
    sa.Column('preferred_education', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_biodatas_id'), 'biodatas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biodatas_id'), table_name='biodatas')
    op.drop_table('biodatas')
    # ### end Alembic commands ###
