"""add biodata preference fields

Revision ID: bb94af002945
Revises: 023fd7085719
Create Date: 2026-07-23 00:08:48.746536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb94af002945'
down_revision: Union[str, Sequence[str], None] = '023fd7085719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "biodatas",
        sa.Column("preferred_height", sa.String(length=50), nullable=True),
    )

    op.add_column(
        "biodatas",
        sa.Column("preferred_religion", sa.String(length=100), nullable=True),
    )

    op.add_column(
        "biodatas",
        sa.Column("preferred_caste", sa.String(length=100), nullable=True),
    )

    op.add_column(
        "biodatas",
        sa.Column("preferred_occupation", sa.String(length=255), nullable=True),
    )

    op.add_column(
        "biodatas",
        sa.Column("preferred_location", sa.String(length=255), nullable=True),
    )

    op.add_column(
        "biodatas",
        sa.Column("expectations", sa.String(length=1000), nullable=True),
    )

    op.add_column(
        "biodatas",
        sa.Column("profile_photo", sa.String(length=500), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biodatas', 'profile_photo')
    op.drop_column('biodatas', 'expectations')
    op.drop_column('biodatas', 'preferred_location')
    op.drop_column('biodatas', 'preferred_occupation')
    op.drop_column('biodatas', 'preferred_caste')
    op.drop_column('biodatas', 'preferred_religion')
    op.drop_column('biodatas', 'preferred_height')
    # ### end Alembic commands ###
